spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book-network
    username: book
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: marcin
    password: marcin
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  ai:
    openai:
      api-key: PROVIDE_YOUR_API_KEY

application:
  security:
    jwt:
      secret-key: 856fb00e45b257e4985b4d71d7cc915ba076a3248d89eb4d4cd376cb1666e92a
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8088