spring:
  application:
      name: book-network-api
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  jpa:
    open-in-view: false
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
